<h1>Language Model Using Tensorflow & keras<h1> 

<h5>Importing Libraries<h5>

In [1]:
from numpy import array
import tensorflow as tf
print(tf.version.VERSION)
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Embedding

/home/joydeb/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/joydeb/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/joydeb/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/joydeb/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: 

1.14.0


<h5>Preprocessing Data<h5>

In [20]:
class Preprocessing():
    
    def __init__(self,input_file):
        self.input_data_file = input_file
        self.data = None
        self.vocab_size = None
        self.encoded_data = None
        self.max_length = None
        self.seq_len = 3
        self.sequences = None
        self.x = None
        self.y = None
    
    def load_data(self):
        fp = open(self.input_data_file,'r')
        self.data = fp.read().splitlines()        
        fp.close()
        
    def encode_data(self):
        tokenizer = Tokenizer()
        tokenizer.fit_on_texts(self.data)
        self.encoded_data = tokenizer.texts_to_sequences(self.data)
        self.vocab_size = len(tokenizer.word_counts)+1
        print("encoded: {}".format(self.encoded_data))
        print("Data: {}".format(self.data))
    def get_sequence(self):
        seq_list = list()
        for item in self.encoded_data:
            l = len(item)
            stop_len = l-self.seq_len+1
            for id in range(stop_len):
                seq_list.append(item[id:id+self.seq_len])
        
        self.max_length = max([len(seq) for seq in seq_list])
        self.sequences = pad_sequences(seq_list, maxlen=self.max_length, padding='pre')
        self.sequences = array(self.sequences)
        print("sequences: {}".format(self.sequences))
            
    def get_data(self):
        self.x = self.sequences[:,:-1]
        self.y = self.sequences[:,-1]
        self.y = to_categorical(self.y,num_classes=self.vocab_size)
        print("X: {}".format(self.x))
        print("Y: {}".format(self.y))
pr = Preprocessing('data.txt')
pr.load_data()
pr.encode_data()
pr.get_sequence()
pr.get_data()

encoded: [[2, 1, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13], [2, 14, 15, 1, 16, 17, 18], [1, 3, 19, 20, 21]]
Data: ['Jack and Jill went up the hill', 'To fetch a pail of water', 'Jack fell down and broke his crown', 'And Jill came tumbling after']
sequences: [[ 2  1  3]
 [ 1  3  4]
 [ 3  4  5]
 [ 4  5  6]
 [ 5  6  7]
 [ 8  9 10]
 [ 9 10 11]
 [10 11 12]
 [11 12 13]
 [ 2 14 15]
 [14 15  1]
 [15  1 16]
 [ 1 16 17]
 [16 17 18]
 [ 1  3 19]
 [ 3 19 20]
 [19 20 21]]
X: [[ 2  1]
 [ 1  3]
 [ 3  4]
 [ 4  5]
 [ 5  6]
 [ 8  9]
 [ 9 10]
 [10 11]
 [11 12]
 [ 2 14]
 [14 15]
 [15  1]
 [ 1 16]
 [16 17]
 [ 1  3]
 [ 3 19]
 [19 20]]
Y: [[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 

In [19]:
class language_model():
    def __init__(self,data,params):
        self.data = data
        self.model = None
        self.tokenizer = None
        self.max_length = None
        self.params = params
        self.x = None
        self.y = None
        self.voacb_size = None
        
    def preprocessing(self):
        
        # integer encode sequences of words
        self.tokenizer = Tokenizer()
        self.tokenizer.fit_on_texts([data])
        print("Data: {}".format([data]))
        encoded = self.tokenizer.texts_to_sequences([data])[0]
        
        # retrieve vocabulary size
        self.vocab_size = len(self.tokenizer.word_index) + 1
        
        print('Vocabulary Size: %d' % self.vocab_size)
        
        # encode 2 words -> 1 word
        sequences = list()
        for i in range(2, len(encoded)):
            sequence = encoded[i-2:i+1]
            sequences.append(sequence)
        print('Total Sequences: %d' % len(sequences))
        print("encoded: {}".format(encoded))
        print("sequences: {}".format(sequences))
        
        # pad sequences
        self.max_length = max([len(seq) for seq in sequences])
        sequences = pad_sequences(sequences, maxlen=self.max_length, padding='pre')
        print('Max Sequence Length: %d' % self.max_length)
        
        # split into input and output elements
        sequences = array(sequences)
        self.x, self.y = sequences[:,:-1],sequences[:,-1]
        self.y = to_categorical(self.y, num_classes=self.vocab_size)
        print("X: {}".format(self.x))
        print("Y: {}".format(self.y))
        
    def define_model(self):
        self.model = Sequential()
        self.model.add(Embedding(self.vocab_size, 10, input_length=self.max_length-1))
        self.model.add(LSTM(50))
        self.model.add(Dense(self.vocab_size, activation=self.params["activation"]))
    
    def create_model(self):
        # compile network
        self.model.compile(loss='categorical_crossentropy', optimizer=self.params['optimizer'], 
                           metrics=self.params["metrics"])
        # fit network
        self.model.fit(self.x, self.y, epochs=self.params["epochs"], verbose=self.params["verbose"])
    
    # generate a sequence from a language model
    def generate_seq(self,seed_text, n_words):
        in_text = seed_text
        # generate a fiselxed number of words
        for _ in range(n_words):
            # encode the text as integer
            encoded = self.tokenizer.texts_to_sequences([in_text])[0]
            # pre-pad sequences to a fixed length
            encoded = pad_sequences([encoded], maxlen=self.max_length-1, padding='pre')
            # predict probabilities for each word
            yhat = self.model.predict_classes(encoded, verbose=0)
            # map predicted word index to word
            out_word = ''
            for word, index in self.tokenizer.word_index.items():
                if index == yhat:
                    out_word = word
                    break
            # append to input
            in_text += ' ' + out_word
        return in_text

# source text
data = """ Jack and Jill went up the hill\n
        To fetch a pail of water\n
        Jack fell down and broke his crown\n
        And Jill came tumbling after\n """

params = {"activation":"softmax","epochs":500,"verbose":2,"loss":"categorical_crossentropy",
          "optimizer":"adam","metrics":['accuracy']}


lang_model = language_model(data,params)
lang_model.preprocessing()
#lang_model.define_model()
#lang_model.create_model()

# define model

print(lang_model.model.summary())

# evaluate model
print(lang_model.generate_seq('Jack and', 5))
print(lang_model.generate_seq('And Jill', 3))
print(lang_model.generate_seq('fell down', 5))
print(lang_model.generate_seq('pail of', 5))

Data: [' Jack and Jill went up the hill\n\n        To fetch a pail of water\n\n        Jack fell down and broke his crown\n\n        And Jill came tumbling after\n ']
Vocabulary Size: 22
Total Sequences: 23
encoded: [2, 1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 2, 14, 15, 1, 16, 17, 18, 1, 3, 19, 20, 21]
sequences: [[2, 1, 3], [1, 3, 4], [3, 4, 5], [4, 5, 6], [5, 6, 7], [6, 7, 8], [7, 8, 9], [8, 9, 10], [9, 10, 11], [10, 11, 12], [11, 12, 13], [12, 13, 2], [13, 2, 14], [2, 14, 15], [14, 15, 1], [15, 1, 16], [1, 16, 17], [16, 17, 18], [17, 18, 1], [18, 1, 3], [1, 3, 19], [3, 19, 20], [19, 20, 21]]
Max Sequence Length: 3
X: [[ 2  1]
 [ 1  3]
 [ 3  4]
 [ 4  5]
 [ 5  6]
 [ 6  7]
 [ 7  8]
 [ 8  9]
 [ 9 10]
 [10 11]
 [11 12]
 [12 13]
 [13  2]
 [ 2 14]
 [14 15]
 [15  1]
 [ 1 16]
 [16 17]
 [17 18]
 [18  1]
 [ 1  3]
 [ 3 19]
 [19 20]]
Y: [[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 

AttributeError: 'NoneType' object has no attribute 'summary'